// React bundle entry point
// This file re-exports React from the installed package
import React, {
  useState,
  useEffect,
  useCallback,
  useMemo,
  useRef,
  useContext,
  useReducer,
  useLayoutEffect,
  useImperativeHandle,
  useId,
  useSyncExternalStore,
  useInsertionEffect,
  Fragment,
  StrictMode,
  Suspense,
  createElement,
  cloneElement,
  isValidElement,
  Children,
  Component,
  PureComponent,
  createContext,
  forwardRef,
  memo,
  lazy,
  startTransition,
  useTransition,
  useDeferredValue,
  useActionState,
  useOptimistic,
  use,
  cache,
} from "react";

// 导出所有命名导出
export {
  useState,
  useEffect,
  useCallback,
  useMemo,
  useRef,
  useContext,
  useReducer,
  useLayoutEffect,
  useImperativeHandle,
  useId,
  useSyncExternalStore,
  useInsertionEffect,
  Fragment,
  StrictMode,
  Suspense,
  createElement,
  cloneElement,
  isValidElement,
  Children,
  Component,
  PureComponent,
  createContext,
  forwardRef,
  memo,
  lazy,
  startTransition,
  useTransition,
  useDeferredValue,
  useActionState,
  useOptimistic,
  use,
  cache,
};

// 导出默认导出
export default React;

